version: "3.8"
services:
  api:
    depends_on:
      - db
      - processor
    environment:
      DB_HOST: db
      DB_NAME: manager
      PDFPROCESSOR_URL: processor:9000
    image: docker.pkg.github.com/dgmann/document-manager/api:latest
    networks:
      backend: null
    volumes:
      - type: volume
        source: records
        target: /records
      - type: volume
        source: archive
        target: /archive
  app:
    environment:
      API_HOST: localhost
      ENABLE_SSL: "false"
    image: docker.pkg.github.com/dgmann/document-manager/app:latest
    networks:
      backend: null
  db:
    image: mongo:latest
    networks:
      backend: null
    volumes:
      - type: volume
        source: mongo
        target: /data/db
  fax_watcher:
    depends_on:
      - api
    environment:
      DESTINATION: http://api/api
      PARSER: fax
    image: docker.pkg.github.com/dgmann/document-manager/directory-watcher:latest
    networks:
      backend: null
    volumes:
      - type: volume
        source: fax
        target: /records
  gateway:
    depends_on:
      - api
      - app
      - m1-adapter
    image: docker.pkg.github.com/dgmann/document-manager/gateway:latest
    networks:
      backend: null
    ports:
      - mode: ingress
        target: 80
        published: 80
        protocol: tcp
  m1-adapter:
    image: docker.pkg.github.com/dgmann/document-manager/m1-adapter:latest
    networks:
      backend: null
  migrator:
    depends_on:
      - api
    environment:
      API_URL: http://api/api
      DB_HOST: mssql
      DB_NAME: PdfDatabase
      DB_PASSWORD: demo
      DB_USER: migration
    image: docker.pkg.github.com/dgmann/document-manager/migrator:latest
    networks:
      backend: null
    ports:
      - mode: ingress
        target: 8080
        published: 8080
        protocol: tcp
    volumes:
      - type: volume
        source: migrator-records
        target: /records
      - type: volume
        source: migrator-data
        target: /data
  processor:
    build:
      context: ./pdf-processor
    networks:
      backend: null
  scan_watcher:
    depends_on:
      - api
    environment:
      DESTINATION: http://api/api
      PARSER: generic
      SENDER: Scan
    image: docker.pkg.github.com/dgmann/document-manager/directory-watcher:latest
    networks:
      backend: null
    volumes:
      - type: volume
        source: scans
        target: /records
networks:
  backend: {}
volumes:
  archive: {}
  fax: {}
  migrator-data: {}
  migrator-records: {}
  mongo: {}
  records: {}
  scans: {}
