version: "3"
services:
  api:
    depends_on:
      - db
      - processor
    environment:
      DB_HOST: db
      DB_NAME: manager
      PDFPROCESSOR_URL: processor:9000
    image: ghcr.io/dgmann/document-manager/api:latest
    networks:
      backend: null
    volumes:
      - records:/records
      - archive:/archive
  app:
    environment:
      API_HOST: localhost
      ENABLE_SSL: "false"
    image: ghcr.io/dgmann/document-manager/app:latest
    networks:
      backend: null
  db:
    image: mongo:latest
    networks:
      backend: null
    volumes:
      - mongo
  fax_watcher:
    depends_on:
      - api
    environment:
      DESTINATION: http://api/api
      PARSER: fax
    image: ghcr.io/dgmann/document-manager/directory-watcher:latest
    networks:
      backend: null
    volumes:
      - fax:/records
  gateway:
    depends_on:
      - api
      - app
      - m1-adapter
    image: ghcr.io/dgmann/document-manager/gateway:latest
    networks:
      backend: null
    ports:
      - 80:80
  m1-adapter:
    image: ghcr.io/dgmann/document-manager/m1-adapter:latest
    networks:
      backend: null
  migrator:
    depends_on:
      - api
    environment:
      API_URL: http://api/api
      DB_HOST: mssql
      DB_NAME: PdfDatabase
      DB_PASSWORD: demo
      DB_USER: migration
    image: ghcr.io/dgmann/document-manager/migrator:latest
    networks:
      backend: null
    ports:
      - 8080:8080
    volumes:
      - migrator-records
      - migrator-data
  processor:
    image: ghcr.io/dgmann/document-manager/pdf-processor:latest
    networks:
      backend: null
  scan_watcher:
    depends_on:
      - api
    environment:
      DESTINATION: http://api/api
      PARSER: generic
      SENDER: Scan
    image: ghcr.io/dgmann/document-manager/directory-watcher:latest
    networks:
      backend: null
    volumes:
      - scans:/records
networks:
  backend: {}
volumes:
  archive: {}
  fax: {}
  migrator-data: {}
  migrator-records: {}
  mongo: {}
  records: {}
  scans: {}
