version: "3"
services:

  gateway:
    image: nginx:alpine
    volumes:
      - ./gateway/config.nginx:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - backend
    depends_on:
      - api
      - app
      - m1-adapter
  db:
    image: mongo:latest
    networks:
      - backend
    ports:
      - "27017:27017"
    volumes:
      - "mongo:/data/db"
  processor:
    build: ./pdf-processor
    ports:
      - "8181:8181"
      - "9000:9000"
    networks:
      - backend
  api:
    build: ./api
    volumes:
      - "E:/mounts/records:/records"
      - "E:/mounts/archive:/archive"
    environment:
      - DB_HOST=db
      - DB_NAME=manager
      - PDFPROCESSOR_URL=processor:9000
      - BASE_URL=http://localhost:8080
      - RELEASE_STAGE=development
      - BUGSNAG_API_KEY=1199963e39770335f40ec3c3228a7390
    networks:
      - backend
    depends_on:
      - db
      - processor
  app:
    build: ./app
    environment:
      - API_URL=http://localhost:8080
      - WS_URL=ws://localhost:8080/notifications
      - BUGSNAG_KEY=44bd0ddb1369a54aa3cfa44bdf04f21c
    networks:
      - backend
  fax_watcher:
    build: ./directory-watcher
    environment:
      - DESTINATION=http://api
      - PARSER=fax
    depends_on:
      - api
    networks:
      - backend
    volumes:
      - "./fax:/records"
  scan_watcher:
      build: ./directory-watcher
      environment:
        - DESTINATION=http://api
        - PARSER=generic
        - SENDER=Scan
      depends_on:
        - api
      networks:
        - backend
      volumes:
        - "./scan:/records"
  m1-adapter:
      build: ./m1-adapter
      environment:
        PORT: "80"
        DB_USERNAME: "m1"
        DB_PASSWORD: "a7haj9"
        DB_HOST: "192.168.255.103"
      networks:
      - backend
  migrator:
    build:
      context: ./migrator
      args:
        GITHUB_TOKEN: ""
    volumes:
      - "./migrator/mounts/records:/records"
      - "./migrator/mounts/data:/data"
      - "./migrator/mounts/splitted:/splitted"
    depends_on:
      - mssql
    networks:
      - backend
      - legacy
    environment:
      - DB_HOST=mssql
      - DB_USER=sa
      - DB_PASSWORD=Password%
      - DB_NAME=PdfDatabase
      - DB_INSTANCE=
      - RECORD_DIR=/records
      - VALIDATION_FILE=/data/validation.log
      - SPLITTED_DIR=/splitted
      - DATA_DIR=/data
      - API_URL=http://10.0.0.38:8080
  mssql:
    image: microsoft/mssql-server-linux
    ports:
    - "1433:1433"
    volumes:
    - "./migrator/mounts/db:/var/opt/mssql"
    networks:
      - legacy
    environment:
    - SA_PASSWORD=Password%
    - ACCEPT_EULA=Y
    - MSSQL_PID=Express
networks:
  backend:
  legacy:
volumes:
  mongo: