version: "3"
services:

  db:
    image: mongo:latest
    networks:
      - backend
    ports:
      - "27017:27017"
  processor:
    build: ./pdf-processor
    ports:
      - "8181:8181"
    networks:
      - backend
  api:
    build: ./api
    environment:
      - DB_HOST=db
      - DB_NAME=manager
      - PDFPROCESSOR_URL=http://processor:8181
    networks:
      - backend
    ports:
      - "8080:80"
    depends_on:
      - db
      - processor

networks:
  backend: