CREATE TABLE records (
  id        INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date      TIMESTAMP    DEFAULT NOW(),
  comment   TEXT         DEFAULT '',
  sender    VARCHAR(100) DEFAULT '',
  document  VARCHAR(200) DEFAULT '',
  processed BOOLEAN      DEFAULT FALSE,
  escalated BOOLEAN      DEFAULT FALSE
);

CREATE TABLE pages (
  id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  record_id INT REFERENCES records ON DELETE CASCADE,
  content   TEXT
);
