// Code generated by protoc-gen-go. DO NOT EDIT.
// source: processor.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Rotate struct {
	Content              []byte   `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content,omitempty"`
	Degree               float64  `protobuf:"fixed64,2,opt,name=Degree,proto3" json:"Degree,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rotate) Reset()         { *m = Rotate{} }
func (m *Rotate) String() string { return proto.CompactTextString(m) }
func (*Rotate) ProtoMessage()    {}
func (*Rotate) Descriptor() ([]byte, []int) {
	return fileDescriptor_processor_d1d35504510aa59b, []int{0}
}
func (m *Rotate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rotate.Unmarshal(m, b)
}
func (m *Rotate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rotate.Marshal(b, m, deterministic)
}
func (dst *Rotate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rotate.Merge(dst, src)
}
func (m *Rotate) XXX_Size() int {
	return xxx_messageInfo_Rotate.Size(m)
}
func (m *Rotate) XXX_DiscardUnknown() {
	xxx_messageInfo_Rotate.DiscardUnknown(m)
}

var xxx_messageInfo_Rotate proto.InternalMessageInfo

func (m *Rotate) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *Rotate) GetDegree() float64 {
	if m != nil {
		return m.Degree
	}
	return 0
}

type Pdf struct {
	Content              []byte   `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pdf) Reset()         { *m = Pdf{} }
func (m *Pdf) String() string { return proto.CompactTextString(m) }
func (*Pdf) ProtoMessage()    {}
func (*Pdf) Descriptor() ([]byte, []int) {
	return fileDescriptor_processor_d1d35504510aa59b, []int{1}
}
func (m *Pdf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pdf.Unmarshal(m, b)
}
func (m *Pdf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pdf.Marshal(b, m, deterministic)
}
func (dst *Pdf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pdf.Merge(dst, src)
}
func (m *Pdf) XXX_Size() int {
	return xxx_messageInfo_Pdf.Size(m)
}
func (m *Pdf) XXX_DiscardUnknown() {
	xxx_messageInfo_Pdf.DiscardUnknown(m)
}

var xxx_messageInfo_Pdf proto.InternalMessageInfo

func (m *Pdf) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type Image struct {
	Format               string   `protobuf:"bytes,1,opt,name=Format,proto3" json:"Format,omitempty"`
	Content              []byte   `protobuf:"bytes,2,opt,name=Content,proto3" json:"Content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Image) Reset()         { *m = Image{} }
func (m *Image) String() string { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()    {}
func (*Image) Descriptor() ([]byte, []int) {
	return fileDescriptor_processor_d1d35504510aa59b, []int{2}
}
func (m *Image) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Image.Unmarshal(m, b)
}
func (m *Image) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Image.Marshal(b, m, deterministic)
}
func (dst *Image) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Image.Merge(dst, src)
}
func (m *Image) XXX_Size() int {
	return xxx_messageInfo_Image.Size(m)
}
func (m *Image) XXX_DiscardUnknown() {
	xxx_messageInfo_Image.DiscardUnknown(m)
}

var xxx_messageInfo_Image proto.InternalMessageInfo

func (m *Image) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

func (m *Image) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func init() {
	proto.RegisterType((*Rotate)(nil), "api.Rotate")
	proto.RegisterType((*Pdf)(nil), "api.Pdf")
	proto.RegisterType((*Image)(nil), "api.Image")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PdfProcessorClient is the client API for PdfProcessor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PdfProcessorClient interface {
	// Convert the pages of a PDF file to images.
	//
	// Convert the pages of a PDF file to images.
	ConvertPdfToImage(ctx context.Context, in *Pdf, opts ...grpc.CallOption) (PdfProcessor_ConvertPdfToImageClient, error)
	RotateImage(ctx context.Context, in *Rotate, opts ...grpc.CallOption) (*Image, error)
}

type pdfProcessorClient struct {
	cc *grpc.ClientConn
}

func NewPdfProcessorClient(cc *grpc.ClientConn) PdfProcessorClient {
	return &pdfProcessorClient{cc}
}

func (c *pdfProcessorClient) ConvertPdfToImage(ctx context.Context, in *Pdf, opts ...grpc.CallOption) (PdfProcessor_ConvertPdfToImageClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PdfProcessor_serviceDesc.Streams[0], "/api.PdfProcessor/ConvertPdfToImage", opts...)
	if err != nil {
		return nil, err
	}
	x := &pdfProcessorConvertPdfToImageClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PdfProcessor_ConvertPdfToImageClient interface {
	Recv() (*Image, error)
	grpc.ClientStream
}

type pdfProcessorConvertPdfToImageClient struct {
	grpc.ClientStream
}

func (x *pdfProcessorConvertPdfToImageClient) Recv() (*Image, error) {
	m := new(Image)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *pdfProcessorClient) RotateImage(ctx context.Context, in *Rotate, opts ...grpc.CallOption) (*Image, error) {
	out := new(Image)
	err := c.cc.Invoke(ctx, "/api.PdfProcessor/RotateImage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PdfProcessorServer is the server API for PdfProcessor service.
type PdfProcessorServer interface {
	// Convert the pages of a PDF file to images.
	//
	// Convert the pages of a PDF file to images.
	ConvertPdfToImage(*Pdf, PdfProcessor_ConvertPdfToImageServer) error
	RotateImage(context.Context, *Rotate) (*Image, error)
}

func RegisterPdfProcessorServer(s *grpc.Server, srv PdfProcessorServer) {
	s.RegisterService(&_PdfProcessor_serviceDesc, srv)
}

func _PdfProcessor_ConvertPdfToImage_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Pdf)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PdfProcessorServer).ConvertPdfToImage(m, &pdfProcessorConvertPdfToImageServer{stream})
}

type PdfProcessor_ConvertPdfToImageServer interface {
	Send(*Image) error
	grpc.ServerStream
}

type pdfProcessorConvertPdfToImageServer struct {
	grpc.ServerStream
}

func (x *pdfProcessorConvertPdfToImageServer) Send(m *Image) error {
	return x.ServerStream.SendMsg(m)
}

func _PdfProcessor_RotateImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Rotate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PdfProcessorServer).RotateImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.PdfProcessor/RotateImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PdfProcessorServer).RotateImage(ctx, req.(*Rotate))
	}
	return interceptor(ctx, in, info, handler)
}

var _PdfProcessor_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.PdfProcessor",
	HandlerType: (*PdfProcessorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RotateImage",
			Handler:    _PdfProcessor_RotateImage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ConvertPdfToImage",
			Handler:       _PdfProcessor_ConvertPdfToImage_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "processor.proto",
}

func init() { proto.RegisterFile("processor.proto", fileDescriptor_processor_d1d35504510aa59b) }

var fileDescriptor_processor_d1d35504510aa59b = []byte{
	// 198 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x28, 0xca, 0x4f,
	0x4e, 0x2d, 0x2e, 0xce, 0x2f, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2c, 0xc8,
	0x54, 0xb2, 0xe2, 0x62, 0x0b, 0xca, 0x2f, 0x49, 0x2c, 0x49, 0x15, 0x92, 0xe0, 0x62, 0x77, 0xce,
	0xcf, 0x2b, 0x49, 0xcd, 0x2b, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x09, 0x82, 0x71, 0x85, 0xc4,
	0xb8, 0xd8, 0x5c, 0x52, 0xd3, 0x8b, 0x52, 0x53, 0x25, 0x98, 0x14, 0x18, 0x35, 0x18, 0x83, 0xa0,
	0x3c, 0x25, 0x79, 0x2e, 0xe6, 0x80, 0x94, 0x34, 0xdc, 0x1a, 0x95, 0x2c, 0xb9, 0x58, 0x3d, 0x73,
	0x13, 0xd3, 0x53, 0x41, 0x26, 0xb8, 0xe5, 0x17, 0xe5, 0x26, 0x42, 0x54, 0x70, 0x06, 0x41, 0x79,
	0xc8, 0x5a, 0x99, 0x50, 0xb4, 0x1a, 0xa5, 0x73, 0xf1, 0x04, 0xa4, 0xa4, 0x05, 0xc0, 0x9c, 0x2c,
	0xa4, 0xcb, 0x25, 0xe8, 0x9c, 0x9f, 0x57, 0x96, 0x5a, 0x54, 0x12, 0x90, 0x92, 0x16, 0x92, 0x0f,
	0x31, 0x96, 0x43, 0x2f, 0xb1, 0x20, 0x53, 0x2f, 0x20, 0x25, 0x4d, 0x8a, 0x0b, 0xcc, 0x02, 0x8b,
	0x2a, 0x31, 0x18, 0x30, 0x0a, 0x69, 0x70, 0x71, 0x43, 0xbc, 0x05, 0x51, 0xc8, 0x0d, 0x96, 0x86,
	0x88, 0xa0, 0xaa, 0x4d, 0x62, 0x03, 0x07, 0x86, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x35, 0x76,
	0xad, 0x51, 0x1f, 0x01, 0x00, 0x00,
}
