version: "3"

services:
  migrator:
    build: .
    environment:
      - DB_HOST=db
      - DB_USER=sa
      - DB_PASSWORD=Password%
      - DB_NAME=PdfDatabase
      - RECORD_DIR=/records
    volumes:
      - "./mounts/records:/records"
