version: '3'
services:

  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - VARIANT=1.22-bookworm
    volumes:
      - ../:/workspaces:cache
      - data:/data
    environment:
      - ARCHIVE_DIR=/data/archive
      - RECORD_DIR=/data/records
      - MQTT_BROKER=mqtt://localhost:1883
      - OTEL_COLLECTOR_URL=localhost:4317
      - API_URL=http://localhost:8181/api
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    cap_add:
    - SYS_PTRACE
    security_opt:
    - seccomp:unconfined
    networks:
      - observability

  db:
    image: 'mongo:6'
    volumes:
      - 'mongo:/data/db'
    restart: unless-stopped
    network_mode: service:app

  mqtt:
    image: emqx:latest
    volumes:
      - emqx-data:/opt/emqx/data
      - emqx-etc:/opt/emqx/etc
      - emqx-log:/opt/emqx/log
    network_mode: service:app
    environment:
      EMQX_MQTT__MAX_MQUEUE_LEN: "infinity"
      EMQX_FORCE_SHUTDOWN__MAX_HEAP_SIZE: "200MB" # Default is 32MB. Higher heap size allows mqueue to grow larger. Can be tuned to fit the system

  otel-collector:
    image: otel/opentelemetry-collector-contrib
    command: [ "--config=/etc/otel-collector.yaml" ]
    network_mode: service:app
    volumes:
      - ./config/otel-collector.yaml:/etc/otel-collector.yaml

  # To eventually offload to Tempo...
  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./config/tempo.yaml:/etc/tempo.yaml
      - tempo-data:/tmp/tempo
    ports:
      - "14268"  # jaeger ingest
      - "3200"   # tempo
      - "4317"  # otlp grpc
      - "4318"  # otlp http
      - "9411"   # zipkin
    networks:
      - observability

  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
      - --enable-feature=otlp-write-receiver
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"
    networks:
      - observability

  grafana:
    image: grafana/grafana:10.1.1
    volumes:
      - ./config/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    network_mode: service:app

volumes:
  mongo: {}
  emqx-data: {}
  emqx-etc: {}
  emqx-log: {}
  data: {}
  tempo-data: {}

networks:
  observability: {}