basePath: /api
consumes:
  - application/json
  - multipart/form-data
host: localhost
info:
  description: The purpose of this application is to provide an api to store uploaded
    PDFs as images and serve them to various frontends
  termsOfService: there are no TOS at this moment, use at your own risk we take no
    responsibility
  title: DocumentManager API.
  version: 0.0.1
paths:
  /records:
    get:
      consumes:
        - application/json
      description: |-
        This will show you all available records by default.
        You can filter the records by status and limit the result through pagination.
      operationId: records
      produces:
        - application/json
      responses:
        "200":
          $ref: '#/responses/DataResponse'
        "500":
          $ref: '#/responses/ErrorResponse'
      summary: Returns all records. Supports filtering by status and pagination
produces:
  - application/json
responses:
  BinaryResponse:
    description: |-
      Binary HTTP Response

      A BinaryResponse is a Response which returns binary data.
    headers:
      Data:
        items:
          format: uint8
          type: integer
        type: array
      StatusCode:
        format: int64
        type: integer
  DataResponse:
    description: |-
      Data HTTP Response

      A DataResponse is a Response which provides additional data as a payload.
    headers:
      Data: {}
      StatusCode:
        format: int64
        type: integer
    schema:
      type: object
  ErrorResponse:
    description: |-
      Error HTTP Response

      A ErrorResponse indicates an error and provides the error message.
    headers:
      Error:
        type: string
      StatusCode:
        format: int64
        type: integer
schemes:
  - http
swagger: "2.0"
