// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: processor.proto

package processor

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PdfProcessor_ConvertPdfToImage_FullMethodName = "/processor.PdfProcessor/ConvertPdfToImage"
	PdfProcessor_RotateImage_FullMethodName       = "/processor.PdfProcessor/RotateImage"
	PdfProcessor_CreatePdf_FullMethodName         = "/processor.PdfProcessor/CreatePdf"
)

// PdfProcessorClient is the client API for PdfProcessor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PdfProcessorClient interface {
	// Convert the pages of a PDF file to images.
	//
	// Convert the pages of a PDF file to images.
	ConvertPdfToImage(ctx context.Context, in *Pdf, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Image], error)
	RotateImage(ctx context.Context, in *Rotate, opts ...grpc.CallOption) (*Image, error)
	CreatePdf(ctx context.Context, in *Document, opts ...grpc.CallOption) (*Pdf, error)
}

type pdfProcessorClient struct {
	cc grpc.ClientConnInterface
}

func NewPdfProcessorClient(cc grpc.ClientConnInterface) PdfProcessorClient {
	return &pdfProcessorClient{cc}
}

func (c *pdfProcessorClient) ConvertPdfToImage(ctx context.Context, in *Pdf, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Image], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PdfProcessor_ServiceDesc.Streams[0], PdfProcessor_ConvertPdfToImage_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Pdf, Image]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PdfProcessor_ConvertPdfToImageClient = grpc.ServerStreamingClient[Image]

func (c *pdfProcessorClient) RotateImage(ctx context.Context, in *Rotate, opts ...grpc.CallOption) (*Image, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Image)
	err := c.cc.Invoke(ctx, PdfProcessor_RotateImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pdfProcessorClient) CreatePdf(ctx context.Context, in *Document, opts ...grpc.CallOption) (*Pdf, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Pdf)
	err := c.cc.Invoke(ctx, PdfProcessor_CreatePdf_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PdfProcessorServer is the server API for PdfProcessor service.
// All implementations must embed UnimplementedPdfProcessorServer
// for forward compatibility.
type PdfProcessorServer interface {
	// Convert the pages of a PDF file to images.
	//
	// Convert the pages of a PDF file to images.
	ConvertPdfToImage(*Pdf, grpc.ServerStreamingServer[Image]) error
	RotateImage(context.Context, *Rotate) (*Image, error)
	CreatePdf(context.Context, *Document) (*Pdf, error)
	mustEmbedUnimplementedPdfProcessorServer()
}

// UnimplementedPdfProcessorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPdfProcessorServer struct{}

func (UnimplementedPdfProcessorServer) ConvertPdfToImage(*Pdf, grpc.ServerStreamingServer[Image]) error {
	return status.Errorf(codes.Unimplemented, "method ConvertPdfToImage not implemented")
}
func (UnimplementedPdfProcessorServer) RotateImage(context.Context, *Rotate) (*Image, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RotateImage not implemented")
}
func (UnimplementedPdfProcessorServer) CreatePdf(context.Context, *Document) (*Pdf, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePdf not implemented")
}
func (UnimplementedPdfProcessorServer) mustEmbedUnimplementedPdfProcessorServer() {}
func (UnimplementedPdfProcessorServer) testEmbeddedByValue()                      {}

// UnsafePdfProcessorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PdfProcessorServer will
// result in compilation errors.
type UnsafePdfProcessorServer interface {
	mustEmbedUnimplementedPdfProcessorServer()
}

func RegisterPdfProcessorServer(s grpc.ServiceRegistrar, srv PdfProcessorServer) {
	// If the following call pancis, it indicates UnimplementedPdfProcessorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PdfProcessor_ServiceDesc, srv)
}

func _PdfProcessor_ConvertPdfToImage_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Pdf)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PdfProcessorServer).ConvertPdfToImage(m, &grpc.GenericServerStream[Pdf, Image]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PdfProcessor_ConvertPdfToImageServer = grpc.ServerStreamingServer[Image]

func _PdfProcessor_RotateImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Rotate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PdfProcessorServer).RotateImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PdfProcessor_RotateImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PdfProcessorServer).RotateImage(ctx, req.(*Rotate))
	}
	return interceptor(ctx, in, info, handler)
}

func _PdfProcessor_CreatePdf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Document)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PdfProcessorServer).CreatePdf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PdfProcessor_CreatePdf_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PdfProcessorServer).CreatePdf(ctx, req.(*Document))
	}
	return interceptor(ctx, in, info, handler)
}

// PdfProcessor_ServiceDesc is the grpc.ServiceDesc for PdfProcessor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PdfProcessor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "processor.PdfProcessor",
	HandlerType: (*PdfProcessorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RotateImage",
			Handler:    _PdfProcessor_RotateImage_Handler,
		},
		{
			MethodName: "CreatePdf",
			Handler:    _PdfProcessor_CreatePdf_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ConvertPdfToImage",
			Handler:       _PdfProcessor_ConvertPdfToImage_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "processor.proto",
}
