version: '3'

services:
  database:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=manager
      - POSTGRES_USER=api
      - POSTGRES_PASSWORD=api
    ports:
      - "5432:5432"
  api:
    build: .
    environment:
      - DB_HOST=database
      - DB_USER=api
      - DB_PASSWORD=api
    ports:
      - "80:80"
    depends_on:
      - database