name: CI

on: 
  pull_request:

env:
  DEVCONTAINER_SUBFOLDER: .github
  DEVCONTAINER_REPOSITORY: "dgmann/document-manager/devcontainer"
  IMAGE_REGISTRY: "ghcr.io"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  devcontainer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          subFolder: ${{ env.DEVCONTAINER_SUBFOLDER }}
          imageName: ${{ env.IMAGE_REGISTRY }}/${{ env.DEVCONTAINER_REPOSITORY }}
          cacheFrom: ${{ env.IMAGE_REGISTRY }}/${{ env.DEVCONTAINER_REPOSITORY }}
          push: always

  ci:
    runs-on: ubuntu-latest
    needs: devcontainer
    strategy:
      fail-fast: false
      matrix:
        app:
          - api
          - directory-watcher
          - frontend
          - m1-adapter
          - m1-helper
          - ocr
          - pdf-processor
        include:
          - type: go
          - app: frontend
            type: node
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and run dev container task (Go)
        uses: devcontainers/ci@v0.3
        if: matrix.type == 'go'
        with:
          configFile: ${{ env.DEVCONTAINER_SUBFOLDER }}/.devcontainer/devcontainer.json
          imageName: ${{ env.IMAGE_REGISTRY }}/${{ env.DEVCONTAINER_REPOSITORY }}
          push: never
          runCmd: |
            cd apps/${{ matrix.app }}
            go test ./...
      
      - name: Build and run dev container task (Node)
        uses: devcontainers/ci@v0.3
        if: matrix.type == 'node'
        with:
          configFile: ${{ env.DEVCONTAINER_SUBFOLDER }}/.devcontainer/devcontainer.json
          imageName: ${{ env.IMAGE_REGISTRY }}/${{ env.DEVCONTAINER_REPOSITORY }}
          push: never
          runCmd: |
            cd apps/${{ matrix.app }}
            npm ci
            npm run test

      