name: Build API
on:
  push:
    paths:
      - 'gateway/**'
      - '.github/workflows/gateway-build.yaml'

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: dgmann/document-manager/gateway
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          dockerfile: gateway/Dockerfile
          context: gateway/