on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple

  build:
    needs: [release-please]
    if: ${{ needs.release-please.outputs.releases_created }}
    uses: dgmann/document-manager/.github/workflows/build.yaml@main
    with:
      tag: ${{ needs.release-please.outputs.tag_name }}
    secrets: inherit

  upload:
    needs: [build, release-please]
    if: ${{ needs.release-please.outputs.releases_created }}
    runs-on: ubuntu-latest
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build.outputs.artifact-id }}
          path: out
      - run: |
          gh release upload ${{ needs.release-please.outputs.tag_name }} out/*