on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release.releases_created }}
      tag_name: ${{ steps.release.tag_name }}
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple

  build:
    needs: [release-please]
    if: ${{ needs.release-please.outputs.releases_created == 'true' }}
    uses: dgmann/document-manager/.github/workflows/build.yaml@main
    with:
      tag: ${{ needs.release-please.outputs.tag_name }}
    secrets: inherit